name: workout_tracker
description: "새싹 관악 flutter 실습 프로젝트"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_http: ^1.0.2
  audioplayers: ^6.1.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/
  fonts:
     - family: Jua
       fonts:
         - asset: assets/fonts/Jua-Regular.ttf
     - family: NanumBrushScript
       fonts:
         - asset: assets/fonts/NanumBrushScript-Regular.ttf
